name: dmpal
description: "A DM's noble helper"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter

  bgg_flutter_client:
    path: /Users/a.zhuravchak/pp/bggapi
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  go_router: ^15.1.1
  get_it: ^8.0.3

dev_dependencies:
  build_runner: ^2.4.15
  flutter_gen_runner:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo/
    - assets/notification/

flutter_gen:
  output: lib/gen/
  line_length: 100

  integrations:
    flutter_svg: true
